[package]
name = "gig"
version = "0.1.5"
authors = ["Ian Fabs <ianfabs@outlook.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features=["yaml"]} 
yaml-rust = "0.4"
git2 = "0.8.0"
